services:
  onboarding-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onboarding-front
    ports:
      - "4000:4000"
    env_file:
      - .env.production
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
